title = 'DevHoolagin'
baseURL = 'https://devhoolagin.github.io/'

languageCode = 'en-us'
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

theme = "hugo-blog-awesome"
contentDir = "content"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
[[menu.main]]
  # The page reference (pageRef) is useful for menu highlighting
  # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  pageRef="/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef="posts"
  name = 'Posts'
  url = '/posts/'
  weight = 20
# Commenting out for now- may add later but
#[[menu.main]]
#  pageRef="about"
#  name = 'About'
#  url = '/about/'
#  weight = 30
[[menu.main]]
  name = 'Portfolio'
  url = 'https://threehoolagins.github.io/'
  weight = 30

[params]
  sitename = "DevHoolagin"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/time/format/ for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "DevHoolagin"
  name = "Caleb C"
  description = "A small site with a few of my thoughts and explorations. Hoping to post more in Winter 2025."

[[params.socialIcons]]
name = "github"
url = "https://github.com/ThreeHoolagins"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/calebbcunningham"
